### ISSUE TITLE
Can we use gitignore.io api?

### ISSUE THREAD

**Issue by ChetanKoneru** [xuchunyang/gitignore-templates.el#2]
Hi @xuchunyang , Thanks for the package.
I was thinking if I can persuade you use `https://www.gitignore.io` when your package is requesting the templates. I tried to implement the change myself changing the URL's in 
`gitignore-templates-names ()` and `gitignore-templates (name)` but I have been getting an error

`all-completions: Invalid function: 1`

With my limited emacs-lisp capabilities it will take me forever to get this working.

Api for List of templates

- https://www.gitignore.io/api/list 

Here is a example request for `java`
- https://www.gitignore.io/api/java

**Comment by xuchunyang** [comment]
There is already a package for it, according to https://docs.gitignore.io/install/editor-extensions#gnu-emacs-juan-placencia

**Comment by xuchunyang** [comment]
Here is some code might be helpful.

```elisp
(defun my-url-to-string (url)
  (with-current-buffer (url-retrieve-synchronously url)
    (prog1 (buffer-substring (1+ url-http-end-of-headers)
                             (point-max))
      (kill-buffer))))

(setq names
      (split-string
       (my-url-to-string "https://www.gitignore.io/api/list")
       "[,\n]" t))

(insert
 (my-url-to-string
  (concat "https://www.gitignore.io/api/"
          (completing-read "Template: " names))))
```

**Comment by ChetanKoneru** [comment]
> There is already a package for it, according to https://docs.gitignore.io/install/editor-extensions#gnu-emacs-juan-placencia

Thanks @xuchunyang , I saw that package but I do not use Helm. I use Ivy. But your code worked though. Thank you very much.
